### ISSUE TITLE
Model_issue

### ISSUE THREAD

**Issue by fancytech77** [asixdev0082/line-amchart#1]
Hi, @softdev0411 

I know who you are. As you know, This account was mine. So, I sincerely hope you provide the credentials of this account for me.

Best regards, Eugene.

**Comment by softpluspro12** [comment]
Hi, @fancytech77 
What is your primary maill address?
I will hand over this account by change the primary mail of github.
OK?
Let me know

Best,

**Comment by fancytech77** [comment]
Thanks for understanding my situation.
Plz change the mail to "tomasaut12@gmail.com". This is my primary mail. I will contact you this weekend.

Best.

**Comment by softpluspro12** [comment]
I contacted with your above mail.
please check and let me know!
Thanks
